ds_course = []

web_course = [['FreeCodeCamp: https://www.freecodecamp.org/'],
['Codecademy: https://www.codecademy.com/'],
['Udacity - Front End Web Developer Nanodegree: https://www.udacity.com/course/front-end-web-developer-nanodegree--nd0011'],
['Coursera - Web Design for Everybody: Basics of Web Development & Coding: https://www.coursera.org/specializations/web-design'],
['edX - Introduction to HTML5: https://www.edx.org/course/introduction-to-html5'],
['W3Schools - Web development tutorials: https://www.w3schools.com/'],
['The Odin Project - Web development curriculum: https://www.theodinproject.com/'],
['Full Stack Open - University of Helsinki: https://fullstackopen.com/en/'],
['The Complete Web Developer Course - Udemy: https://www.udemy.com/course/the-complete-web-developer-course-2/'],
['Skillshare - Web Development courses: https://www.skillshare.com/browse/web-development'],
['Mozilla Developer Network - Web development documentation and tutorials: https://developer.mozilla.org/en-US/docs/Learn'],
['LinkedIn Learning - Web Development courses: https://www.linkedin.com/learning/topics/web-development'],
['Treehouse - Web Development courses: https://teamtreehouse.com/tracks/web-development'],
['Webflow University - Web Design and Development courses: https://university.webflow.com/']]

android_course = [['Android Basics Nanodegree - Google: https://www.udacity.com/course/android-basics-nanodegree-by-google--nd803'],
['Android Developer Fundamentals - Google: https://developer.android.com/courses/fundamentals-training/overview-v2'],
['Android App Development Specialization - Coursera: https://www.coursera.org/specializations/android-app-development'],
['Kotlin for Android - Udacity: https://www.udacity.com/course/kotlin-for-android-developers--ud888'],
['Android Developer - Udacity: https://www.udacity.com/course/android-developer-nanodegree--nd801'],
['Android Kotlin Fundamentals - Google: https://developer.android.com/courses/kotlin-android-fundamentals/overview'],
['Android App Development - edX: https://www.edx.org/course/android-app-development]]']]

ios_course = [['iOS App Development with Swift - Coursera: https://www.coursera.org/specializations/app-development'],
['Swift for Beginners - Udacity: https://www.udacity.com/course/swift-for-beginners--ud1022'],
['iOS Developer - Udacity: https://www.udacity.com/course/ios-developer-nanodegree--nd003'],
['Developing iOS 11 Apps with Swift - Stanford University: https://itunes.apple.com/us/course/developing-ios-11-apps-with-swift/id1309275316'],
['iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp - Udemy: https://www.udemy.com/course/ios-11-app-development-bootcamp/'],
['The iOS 10 Developer Bootcamp - Udemy: https://www.udemy.com/course/the-ios-10-developer-bootcamp/'],
['Swift Programming - edX: https://www.edx.org/learn/swift-programming'],
['iOS App Development Essentials - Udacity: https://www.udacity.com/course/ios-app-development-essentials--ud009'],
['iOS Development - Codecademy: https://www.codecademy.com/learn/learn-ios'],
['The Complete iOS 14 App Development Course - Udemy: https://www.udemy.com/course/the-complete-ios-14-app-development-course/'],
['iOS Development with Swift - LinkedIn Learning: https://www.linkedin.com/learning/ios-development-with-swift'],
['Mastering iOS Development - Treehouse: https://teamtreehouse.com/tracks/ios-development'],
['iOS Development for Creative Entrepreneurs - Skillshare: https://www.skillshare.com/classes/iOS-Development-for-Creative-Entrepreneurs/806315722'],
['iOS Development with Swift - Pluralsight: https://www.pluralsight.com/paths/ios-development-with-swift']
]

uiux_course = [['Interaction Design Foundation (https://www.interaction-design.org/)'],
['Udemy UI/UX Design Courses (https://www.udemy.com/topic/ui-ux-design/)'],
['Coursera UI/UX Design Courses (https://www.coursera.org/courses?query=ui%2Fux%20design)'],
['Skillshare UI/UX Design Courses (https://www.skillshare.com/browse/ui-ux-design)'],
['LinkedIn Learning UI/UX Design Courses (https://www.linkedin.com/learning/topics/ui-ux-design)'],
['Hack Design (https://hackdesign.org/) Treehouse UI/UX Design Courses (https://teamtreehouse.com/tracks/user-experience-design)'],
['Smashing Magazine (https://www.smashingmagazine.com/)'],
['DesignLab (https://trydesignlab.com/)'],
['The Futur (https://www.thefutur.com/)'],
['Google Design (https://design.google/education/)'],
['Springboard UI/UX Design Course (https://www.springboard.com/courses/ui-ux-design-career-track/)'],
['UX Mastery (https://uxmastery.com/)'],
['Learn UI Design (https://learnui.design/)'],
['Human Factors International (https://www.humanfactors.com/)']]